name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        # Update package list and install required packages
        sudo apt-get update
        sudo apt-get install -y build-essential

        # Download and install CUnit
        wget https://github.com/CUnit/CUnit/archive/refs/tags/2.1-3.tar.gz
        tar -xzf 2.1-3.tar.gz
        cd CUnit-2.1-3
        ./configure --prefix=/opt/homebrew/Cellar/cunit/2.1-3
        make
        sudo make install

    - name: Set environment variables
      run: |
        echo "/opt/homebrew/Cellar/cunit/2.1-3/lib" >> $GITHUB_ENV
        echo "/opt/homebrew/Cellar/cunit/2.1-3/include" >> $GITHUB_ENV

    - name: Build project
      env:
        CUNIT_LIB: /opt/homebrew/Cellar/cunit/2.1-3/lib
        CUNIT_INCLUDE: /opt/homebrew/Cellar/cunit/2.1-3/include
      run: |
        gcc -I$CUNIT_INCLUDE -L$CUNIT_LIB -o test_main tests/test_main.c -lcunit

    - name: Run tests
      run: ./test_main
